// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6xgT1yGxl6e17bvSizEoOCDXnmPVRwfQ',
    appId: '1:27737929784:web:931711bd597964a2cacecd',
    messagingSenderId: '27737929784',
    projectId: 'scolar-chat-1e876',
    authDomain: 'scolar-chat-1e876.firebaseapp.com',
    storageBucket: 'scolar-chat-1e876.firebasestorage.app',
    measurementId: 'G-90LT681TLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9ApI1VkfJ9MWEMU3P80hEEE_GqfmVwQ',
    appId: '1:27737929784:android:2578972b24709249cacecd',
    messagingSenderId: '27737929784',
    projectId: 'scolar-chat-1e876',
    storageBucket: 'scolar-chat-1e876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIF09CpX3c0ealZsJx9-Bec1lr30i06MM',
    appId: '1:27737929784:ios:513f2d979f93ca36cacecd',
    messagingSenderId: '27737929784',
    projectId: 'scolar-chat-1e876',
    storageBucket: 'scolar-chat-1e876.firebasestorage.app',
    iosBundleId: 'com.example.folder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIF09CpX3c0ealZsJx9-Bec1lr30i06MM',
    appId: '1:27737929784:ios:513f2d979f93ca36cacecd',
    messagingSenderId: '27737929784',
    projectId: 'scolar-chat-1e876',
    storageBucket: 'scolar-chat-1e876.firebasestorage.app',
    iosBundleId: 'com.example.folder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6xgT1yGxl6e17bvSizEoOCDXnmPVRwfQ',
    appId: '1:27737929784:web:be803de11934f72bcacecd',
    messagingSenderId: '27737929784',
    projectId: 'scolar-chat-1e876',
    authDomain: 'scolar-chat-1e876.firebaseapp.com',
    storageBucket: 'scolar-chat-1e876.firebasestorage.app',
    measurementId: 'G-HZF73Y5WFW',
  );

}